In [1]:
# import the required Python libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [13]:
import pandas as pd

data = pd.read_csv("marketing_sample_for_ebay_com-ebay_com_product__20200601_20200831__30k_data.csv")  # หรือใช้ path ที่ตรงกับไฟล์จริง

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29997 entries, 0 to 29996
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Uniq Id            29997 non-null  object
 1   Crawl Timestamp    29997 non-null  object
 2   Pageurl            29997 non-null  object
 3   Website            29997 non-null  object
 4   Title              29997 non-null  object
 5   Num Of Reviews     21990 non-null  float64
 6   Average Rating     22037 non-null  float64
 7   Number Of Ratings  21990 non-null  float64
 8   Model Num          7228 non-null   object
 9   Sku                0 non-null      float64
 10  Upc                19957 non-null  object
 11  Manufacturer       29997 non-null  object
 12  Model Name         29997 non-null  object
 13  Price              23052 non-null  object
 14  Monthly Price      0 non-null      float64
 15  Stock              21689 non-null  object
 16  Carrier            14672 non-null  object
 17  Color Category     18025 non-null  object
 18  Internal Memory    11384 non-null  object
 19  Screen Size        14439 non-null  object
 20  Five Star          20782 non-null  float64
 21  Four Star          20782 non-null  float64
 22  Three Star         20782 non-null  float64
 23  Two Star           20782 non-null  float64
 24  One Star           12908 non-null  float64
dtypes: float64(10), object(15)
memory usage: 5.7+ MB

In [16]:
data.describe()

,Num Of Reviews,Average Rating,Number Of Ratings,Sku,Monthly Price,Five Star,Four Star,Three Star,Two Star,One Star
count,21990.000000,22037.000000,21990.000000,0.0,0.0,20782.000000,20782.000000,20782.000000,20782.000000,12908.000000
mean,117.874443,4.609702,171.020964,NaN,NaN,91.448417,11.962179,3.689828,3.866856,6.128757
std,287.164995,0.482322,448.105444,NaN,NaN,301.114173,36.390284,11.131082,12.261449,17.846552
min,1.000000,1.000000,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.000000,4.500000,5.000000,NaN,NaN,2.000000,0.000000,0.000000,0.000000,0.000000
50%,24.000000,4.700000,33.000000,NaN,NaN,11.000000,2.000000,1.000000,1.000000,1.000000
75%,104.000000,4.900000,145.000000,NaN,NaN,63.000000,9.000000,3.000000,3.000000,5.000000
max,5285.000000,5.000000,9384.000000,NaN,NaN,7655.000000,947.000000,335.000000,336.000000,305.000000

In [17]:
data.head()

,Uniq Id,Crawl Timestamp,Pageurl,Website,Title,Num Of Reviews,Average Rating,Number Of Ratings,Model Num,Sku,...,Stock,Carrier,Color Category,Internal Memory,Screen Size,Five Star,Four Star,Three Star,Two Star,One Star
0,a1c6790e161e88229fffaded7a449bee,2020-08-09 09:04:12 +0000,https://www.ebay.com/p/228620470?iid=264820356235,ebay.com,"Apple iPad Air 2 32GB, Wi-Fi, 9.7in - Silver",39.0,4.8,60.0,A1566,NaN,...,true,Not Applicable,Silver,32 GB,9.7 in,52.0,4.0,2.0,1.0,1.0
1,f1196a5050e55108f6114c21d194baab,2020-08-04 17:48:32 +0000,https://www.ebay.com/p/15035645654?iid=3240760...,ebay.com,Anker Soundcore Liberty 2 Pro Black In-Ear Hea...,5.0,5.0,5.0,NaN,NaN,...,true,NaN,Black,NaN,NaN,5.0,0.0,0.0,0.0,0.0
2,14358f32683693500b21bb26bfadb436,2020-07-10 01:50:55 +0000,https://www.ebay.com/p/1567609178?iid=38286251...,ebay.com,Sony HT-CT790 2.1-Channel Soundbar with Wi-Fi/...,50.0,4.6,65.0,NaN,NaN,...,true,NaN,Black,NaN,NaN,51.0,9.0,1.0,2.0,2.0
3,4000044f1696eb9f5fe35e60e03c3d30,2020-07-18 20:30:57 +0000,https://www.ebay.com/p/8024544561?iid=15320815...,ebay.com,Hmqc Poe Audio 2.0mp 3.6mm 1080p IP Camera P2p...,NaN,NaN,NaN,NaN,NaN,...,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50419e2f9407477fbf397a3a61cec29d,2020-06-28 08:26:36 +0000,https://www.ebay.com/p/18031758326?iid=2936295...,ebay.com,Sony WI-C600N Black In-Ear Headsets,8.0,4.5,12.0,NaN,NaN,...,NaN,Black,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN